//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreHonda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham_MauSac
    {
        public int MaSanPham { get; set; }
        public int MaMauSac { get; set; }
        public string HinhMauSac { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual MauSac MauSac { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
